### ISSUE TITLE
Твое ишью

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JTOne123/moyvkus#1]
```
1. Текущая твоя цель, ща разбить интерфейс и 
логику
т.е. мы должны иметь хтмл файл с дизайном и 
яваскриптом, если такой необходим
и пшп файл с функциональностью этой 
страницы

2. разобраться с локализацией и сразу ее 
заюзать

3. разработать индесовую страницу, таким 
образом каким мы с тобой ее
обсуждали, типа что бы внедрение модулей 
это просто вставка в нужное
место вызыва метода экземпляра класса
```

Original issue reported on code.google.com by `JTHot...@gmail.com` on 20 Mar 2008 at 9:18

**Comment by JTOne123** [comment]
Саша прошло уже 7 лет, а ты никак не можешь закрыть этот таск!

**Comment by sanchos** [comment]
ахах)))

16 марта 2015 г., 10:57 пользователь Paul notifications@github.com
написал:

> Саша прошло уже 7 лет, а ты никак не можешь закрыть этот таск!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JTOne123/moyvkus/issues/1#issuecomment-81513389.

## 

Thanks,
_Alex Verbovsky_
